### ISSUE TITLE
Add support for debug symbols

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-objc#11]
http://code.google.com/p/plcrashreporter/

**Comment by asbjornu** [comment]
What's the requirements? How can someone (like me) help out to get this implemented?

**Comment by dcramer** [comment]
@asbjornu I think a lot of this is figuring out what we even need to do.

As far as I know there will be two requirements:

- Supporting sending whatever applicable payload is needed within the client
- Determining how we deobfuscate things on the server side (which I'm happy to implement)

There's a couple of issues w/ the server side in that we dont currently support uploading of the dsym file, but I'm happy to fix this immediately as we're almost there. 

There also might be a better solution to plcrashreporter, but I think it's still the primary tool for this.

This is probably the main area of work that I can help with: https://groups.google.com/forum/#!topic/plcrashreporter/Ee-HszpJ2jw

I know little to nothing about how it would actually be implemented in raven-objc though

**Comment by jaysoffian** [comment]
FWIW, I'm using Sentry as part of a mobile crash reporting solution. In my particular architecture, I have a receiver and a processor which sit in front of Sentry. The processor is responsible for symbolicating the crashes before sending them to Sentry.

The issue with symbolicating on Linux is that the debug symbols produced by Xcode (dSYM bundle) are in a proprietary format. The way I chose to deal with this is by using the `dump_syms` utility from Google Breakpad to convert the symbols into an easy-to-parse text format. `dump_syms` itself must be run on OS X, and I run it as part of our build process.

Separately, I wrote a Python symbolicator that can symbolicate an Apple crash report (as produced by plcrashreporter).

Squash.io uses a similar design, extracting the debug symbols on OS X and uploading them to its database via an API call.

I'm frankly not sure what the commercial providers (Crashlytics, Crittercism, Splunk nee Bugsense, Microsoft nee HockeyApp) do here. It's possible they've written code to parse dSYM bundles on Linux. Or it's possible they have a bank of OS X machines whose purpose is just to dump symbols from the dSYM's.

**Comment by jaysoffian** [comment]
PLCrashReporter is best-of-class. Almost all the commercial crash solutions make use of it (I believe only Crashlytics has written their own). Next best is probably Google Breakpad, which is what both Google and Mozilla use. Finally there's https://github.com/kstenerud/KSCrash, but I don't know of anyone using it.

**Comment by jaysoffian** [comment]
I guess it wouldn't be rocket science to dump a dSYM on Linux, but I don't know of any readily available code to do so. Some pointers:

https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/MachORuntime/index.html#//apple_ref/c/tag/uuid_command

https://pypi.python.org/pypi/macholib/

http://podgorskiy.com/?p=278

**Comment by dcramer** [comment]
I will work on adding support for them in Sentry. The remainder is figuring out how to send the data. 

I think we're going to make it so plugins can extend interfaces and then we'd have a custom interface for the symbols. 

In addition I'll add file upload support to releases which is the primary missing component. 

I think the best solution will be to write a python tool which can parse the data structures, or use breakpad as Linux is an absolute requirement.

**Comment by jaysoffian** [comment]
Every mobile app developer I know wants the full fidelity of an Apple crash report. That would be a fairly large amount of data for Sentry to hold on to. My implementation sends in a subset of the data, but we keep the original report around on disk and link to it from Sentry. $0.02.

**Comment by dcramer** [comment]
Here's the general plan on what we're implementing right now:

- File storage abstraction https://github.com/getsentry/sentry/pull/1382
- API endpoint to add a unique file to a release (it'll be keyed on filename)
- Plugin2.get_release_artifact_processors() -- returns a list of functions to handle a "new file uploaded to release"
- [likely] Plugin2.get_interfaces -- extension point to register new interfaces. This would let us have a 'symbols' top level key. I'm not sure this is the best solution to this problem yet so we'll give this more thought.

**Comment by thedrow** [comment]
We're really interested in this feature.
We're currently using [Squash](https://github.com/SquareSquash/cocoa) for the iOS app although we are paying getsentry.com because this is not supported.
We really want to move the error reporting to Sentry as soon as possible.
@dcramer Can you open issues on https://github.com/getsentry/sentry/ for the rest of the stuff that needs to be done?

**Comment by dcramer** [comment]
@thedrow if people are willing to help push the objective-c changes we (the Sentry company) are happy to push through the needed API changes

The remaining items on Sentry are actually fairly quick (for us at least, since we're familiar with the code), it's mostly just "how is this going to work".

WIth the direction we're going it should be also technically possible to contain all of the objective-c logic in a plugin as well, though we dont actually have to do that.

I think the main concern here is being able to parse the dSYM (or whatever) files. We definitely dont want to require extra servers/third party services/etc, and I'm not quite certain on how much work it's going to take to reverse those files (or whatever plcrashreporter provides).

**Comment by asbjornu** [comment]
Just to add on to the "me too" list, we want this for [SharpRaven](/getsentry/raven-csharp) too. So perhaps this issue should be mostly about having dSYM support, so we can have a similar issue for SharpRaven on the support of PDB files. Then the main work item issue should probably be hosted in the main [Sentry](/getsentry/sentry) repository. Does such an issue already exist?

**Comment by jaysoffian** [comment]
PDB files can also be handled by Breakpad. They have to be dumped to the "sym" format on a Windows box though, similar to how you'd dump a dSYM to a sym file on an OS X machine. Otherwise it's another binary type to write a parser for.

**Comment by thedrow** [comment]
@dcramer We're paying customers. We don't have the bandwidth to contribute this. We have to focus on our own product.

**Comment by dcramer** [comment]
@thedrow that's fine, but we don't use ObjC ourselves so realistically until we solve a bunch of other issues, or someone steps up to drive the direction of what needs to be done, it's probably not going to be officially supported by Sentry.

**Comment by asbjornu** [comment]
@dcramer As long as you finish off the required bits on the back-end (API changes and such), I'm sure we can get contributions on the dSYM parser and the POSTing of symbol files in the client.

**Comment by dcramer** [comment]
Following up here. We have full support for stored artifacts (though it's still in draft phase) as well as language extensions now.

I'm absolutely willing to sponsor getting this done, but from our point of it will require a processing pipeline that is 100% in python (i.e. doing the transformations using our own code vs any existing libraries that may run under different platforms).

The releases API currently is only built into the JS side of things, but here's how it looks for an end user:

https://gist.github.com/dcramer/619d53dabfbc2ed008a1

**Comment by asbjornu** [comment]
Great work, @dcramer! The API looks simple and shouldn't take too long to get implemented in any of the clients. The hard part seems to be how to get the symbol files converted to a common format that the server is able to parse and make sense of. Have you decided on the format yet?

As @jaysoffian mentions, Breakpad can be used as a converter before uploading the symbol file to the server, but that assumes Breakpad's `sym` format is something the Sentry server supports. Is it?

**Comment by dcramer** [comment]
We don't support anything yet. I think our next step is deciding what the best direction forward is. Well need to write a python solution for mapping symbols but ideally the symbol format is whatever is common place for iOS devs. 






On Mon, Mar 23, 2015 at 3:23 PM -0700, "Asbjørn Ulsberg" <notifications@github.com> wrote:












Great work, @dcramer! The API looks simple and shouldn't take too long to get implemented in any of the clients. The hard part seems to be how to get the symbol files converted to a common format that the server is able to parse and make sense of. Have you decided on the format yet?



As @jaysoffian mentions, Breakpad can be used as a converter before uploading the symbol file to the server, but that assumes Breakpad's sym format is something the Sentry server supports. Is it?

**Comment by jaysoffian** [comment]
Common place is dSYM bundles. They'd typically be zipped and uploaded. You'll need to figure out how to parse these in Python. I've linked earlier in this thread to some Python libs that may help.

http://wiki.dwarfstd.org/index.php?title=Apple's_%22Lazy%22_DWARF_Scheme

**Comment by tutipeti** [comment]
Any news on this one? It's been a while and I still see no sign of uploading my symbol files anywhere.

**Comment by asbjornu** [comment]
@tutipeti I seem to remember @dcramer saying they are close to having Objective C support in place, but I'm not intimate with the details.

**Comment by sideboltconor** [comment]
This would be a killer feature.

**Comment by IanKeen** [comment]
any update on this? has this been forgotten?

**Comment by lukeburden** [comment]
Another paying sentry customer here with a +1 to making this issue a priority.

Sentry is serving us very well on our python-based backend but we're now being forced to consider other options for our mobile apps due to this issue. Advertising Objective-C as a supported language on the Sentry site seems disingenuous to me without this functionality being in place.

**Comment by dcramer** [comment]
@lukeburden fwiw we're actively trying to hire someone to help us with this:

https://www.getsentry.com/jobs/00790FFCE6/

If you have any recs, send them our way!

**Comment by lukeburden** [comment]
@dcramer I feel your pain; it's very hard to find good people I imagine even harder given all the competition in the Bay Area!

Seems the resolution of this issue is an indeterminate number of months away so I'm forced to shift to Fabric for our iOS app for the time being. Keep us up to speed on your progress and good luck with the hiring. :)

**Comment by dcramer** [comment]
@lukeburden give us ~6 weeks :)

(we actually are bringing on a contractor in the short term to help with this)

**Comment by lukeburden** [comment]
@dcramer careful now, that almost looks like a timeline! Seriously though, that's great news. We eagerly await updates. :)

**Comment by timorzadir** [comment]
@dcramer Will this require anything from the iOS clients, or will it be covered by the `Release Tracking` feature?

**Comment by dcramer** [comment]
@timorzadir our goal is to keep familiar processes, but it will require at least some level of effort. Most likely it will require you to push to dsyms to our artifact APIs (similar to how we already accept sourcemaps).

**Comment by asbjornu** [comment]
@dcramer The 6 weeks have passed. What's the status on this feature? :smiley:

**Comment by dcramer** [comment]
Still soon(tm). Our last contractor fell through, but we're talking to someone later this week. Unfortunately with holidays it's likely we wont see support til at least late January.

**Comment by asbjornu** [comment]
@dcramer Late January is better than never. Looking forward to seeing this feature implemented for both Objective C, Swift and C#! :smiley:

**Comment by tutipeti** [comment]
@dcramer sorry for being a pain in the a**, but January is almost over.. Any news? :p

**Comment by dcramer** [comment]
We are still working on this. All I can say is it'll be done when it's done, but we'll likely have some initial server side stuff ready in a few weeks.

**Comment by bcattle** [comment]
I'm sure you guys have put a ton more thought into this than the 15 mins I just spent researching it, but would an easier solution be for the developer to upload a plaintext / easily python-parsable format to you, rather than dSYM? This would be trivial to call at compile-time from XCode and might save you the hassle of trying to build a bunch of dSYM parsing machinery for Linux.  

As I understand it you just need a mapping of symbol addresses to method names. An easy way to obtain this is to run `dwarfdump` on your dSYM, which gives output like 

    0x0002c8fa:     structure type [16] *
                    name( "NSString" )
                    byte size( 0x04 )
                    decl file( "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h" )
                    decl line( 70 )
                    APPLE runtime class( 0x10 )

    0x0002c903:         inheritance [81]  
                        type( {0x00000190} ( NSObject ) )
                        data member location( 0x00 )

    0x0002c909:         APPLE Property [82]  
                        APPLE property name( "length" )
                        type( {0x0002b319} ( NSUInteger ) )
                        decl file( "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h" )
                    decl line( 76 )
                    APPLE property attribute( 0x0101 ( DW_APPLE_PROPERTY_readonly )  )

For end users, this wouldn't be more work from the standpoint that most devs would want an XCode build phase that automatically uploads dSYMs anyway. (See for example how [Crashlytics does this](https://docs.fabric.io/ios/crashlytics/advanced-setup.html#conditional-dsym-upload).) Rather than try to master parsing the dSYM format on Linux/Python, you could re-frame the problem by requiring devs to upload a format you already know how to parse, or that could be implemented easily, or across platforms. 

This is the philosophy of the DWARF format, for example. Perhaps a DWARF-symbolication plugin for Sentry could be made generic enough to support input from MSFT's PDB format, Cocoa, and potentially others.

**Comment by dcramer** [comment]
@bcattle we actually already have implemented parsing. We're working on handling various cases and we will have a new swift client which integrates cleanly.

**Comment by mikepurvis** [comment]
I'm confused why this needs to be implemented as a first-class feature in Sentry itself. Wouldn't it be far simpler to just have a "preprocessor" API, and allow plugins to take care of expanding core dumps into stack traces? Either that, or supply an API for a parallel Jenkins/Rundeck service to generate additional metadata and update issues after the fact.

**Comment by dcramer** [comment]
It might be easier for us but no one would use it. This support is already done so no need to discuss it. Closing this out since new Swift SDK fully supports the flow.

**Comment by mikepurvis** [comment]
Oh okay— wasn't sure if it was done or not, as I'm not using Sentry with iOS, and the ticket was left open.

We would indeed be interested in the ability to preprocess events on their way into Sentry, but I guess you've decided that "no one" would use that, so we'll maybe handle it via Cyclops, or patch in our own extension points.

**Comment by dcramer** [comment]
@mikepurvis I was specifically talking debug symbols as its a common pattern and not simple to do yourself.  We have customers who preprocess before hitting sentry but nothing really prohibits you from doing that. We just don't allow mutation of an event once it's stored.

**Comment by mikepurvis** [comment]
Cool, sounds good. As you say, it is a common pattern— but down the road it would be great to see the functionality moved into plugins so that it's more possible for orgs to easily build integration for custom crash reporters, embedded toolchains, etc.

For example, in our case, generating the stack trace has a non-trivial cost, so it's a bummer to have to do it for every single crash when Sentry's sampling scheme is going to end up tossing some/many of them anyway. If it was something more native, then Sentry could call for post-processing only on those events which it intends to keep around.

What's the rationale for not allowing mutation of an event? It would be extremely convenient to have a webhook system (think github+travis) by which an external-to-sentry service could inject supplementary blobs of content— could be stack traces, but also things like VCS URLs, Jenkins logs, etc.

**Comment by dcramer** [comment]
@mikepurvis our system is designed to be immutable once the event is stored (everything else happens in the process pipeline).

A couple notes:

- We need to know the actual stack before sampling algos get hit
- If you're running on-premise its possible to utilize our extension system  (look how js/native work in core, they're just plugins)

If you have more suggestions, feel free to open a ticket on getsentry/sentry, as I dont think its an unreasonable concept to think about how this could be exposed in the future.

**Comment by mikepurvis** [comment]
Ah, I see: https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/plugin.py

Cool, will investigate this further, thanks!
