### ISSUE TITLE
Crash Reports and Symbolication

### ISSUE THREAD

**Issue by smolls** [getsentry/raven-objc#16]
I see there's an open issue to look into PLCrashReporter. Am I correct in assuming that Sentry doesn't support collecting crash reports and symbolicating them (as of 2013/04/23) ?

**Comment by asbjornu** [comment]
When issue #11 is resolved, I assume this will be taken care of. I'm therefore closing this issue in favour of it. If you have any input on the plan to have this implemented, please provide that there.
