### ISSUE TITLE
New CocoaPods release?

### ISSUE THREAD

**Issue by mlb5000** [getsentry/raven-objc#32]
It looks like there have been some new features since the Pod was last released.  Can you release a new version?

**Comment by lysannschlegel** [comment]
`Raven` needs to be written with a capital R:

```ruby
pod 'Raven', :git => 'https://github.com/getsentry/raven-objc.git', :tag => '0.5.0'
```

Otherwise, that's working fine for now.

**Comment by dcramer** [comment]
Sorry all I'll get this taken care of.

**Comment by dcramer** [comment]
@timorzadir can you let me know what email address you use for cocoapods? feel free to email david at getsentry.

**Comment by dcramer** [comment]
We're all set here now.

**Comment by timorzadir** [comment]
Thanks! 0.5.0 and 1.0.1 are both pushed to cocoapods now.
