### ISSUE TITLE
Support Tracebacks

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-objc#5]
See also GH-11

**Comment by asbjornu** [comment]
I'd love to know what more is required on the back-end to support this. If I understand the requirements and the code in which they are to be implemented well enough, I'm keen on implementing this.

**Comment by thedrow** [comment]
@asbjornu Check #11. @dcramer already described what needs to be done on the server.

**Comment by asbjornu** [comment]
Yea, I guess #11 contains what we need to get all of this sorted out. I'm therefore closing this.
