### ISSUE TITLE
Push 1.0.1 to CocoaPods

### ISSUE THREAD

**Issue by emartynov** [getsentry/raven-objc#50]
Hi guys,

Thank you for the library! Are there reasons why 1.0.1 is not in Cocoapods.org?

Kind Regards,
Eugen

**Comment by timorzadir** [comment]
Have a look at #32 for this.  Short version is that we are waiting for @dcramer to claim the repo.

**Comment by emartynov** [comment]
Thanks! Should first check opened tickets. Sorry!

**Comment by timorzadir** [comment]
No problem, 1.0.1 is now pushed to Cocoapods.
