### ISSUE TITLE
Sentry is reporting errors only from Simulator not working on device.

### ISSUE THREAD

**Issue by virumax** [getsentry/raven-objc#53]
I have used only following two lines to setup sentry in my project in applicationdidfinishlaunchingwithoptions method in appdelegate. However it seems to be work only on simulator when crash occurs, It is not working on actual device at all.

    [RavenClient clientWithDSN:@"https://xxxxxxxxxxxxx@app.getsentry.com/xxxxx"];
    // Install the global error handler
    [[RavenClient sharedClient] setupExceptionHandler];

**Comment by asbjornu** [comment]
The `sharedClient` isn't set up automatically anymore. You need to do the following explicitly before using `sharedClient`:
```objc
RavenClient *client = [RavenClient clientWithDSN:@"https://xxxxxxxxxxxxx@app.getsentry.com/xxxxx"];
// You need to explicitly set the shared client if you want to use the singleton pattern
[RavenClient setSharedClient:client];
```

**Comment by tapannathvani** [comment]
Hello,

I am not getting crash log on my sentry account.

 RavenClient *client = [RavenClient clientWithDSN:@"https://XXXXXX:XXXXX@sentry.abc.com/123"];
    [RavenClient setSharedClient:client];
    [[RavenClient sharedClient] setupExceptionHandler];
