### ISSUE TITLE
Tags are not displayed in Sentry Backend because of spaces

### ISSUE THREAD

**Issue by manuelblum** [getsentry/raven-objc#64]
Since 05. October 2015, Sentry does not display the default Tags provided by raven-objc because the contain spaces. 

According to a mail from a sentry Member it is currently not supported to have tags with spaces.

**Comment by dcramer** [comment]
Slight miscommunication.

They *shouldnt* have spaces, but this shouldn't be breaking things (I didnt test but I examined validation code for it).

Will investigate further.

**Comment by mgv** [comment]
I can confirm. I'm experiencing the same issue.

**Comment by dcramer** [comment]
I was wrong. There was a bit of code discarding these in some legacy paths.
