### ISSUE TITLE
can't directly use in react native `RCTExceptionsManagerDelegate`

### ISSUE THREAD

**Issue by springuper** [getsentry/raven-objc#70]
react native `RCTExceptionsManagerDelegate` has two methods:

- handleSoftJSExceptionWithMessage:stack:exceptionId
- handleFatalJSExceptionWithMessage:stack:exceptionId

neither `captureMessage` nor `captureException` can directly be used for these params. I find a way to use the lower layer method `sendDictionary`, but that needs rewrite a lot of code.

Any ideas?

**Comment by dcramer** [comment]
@springuper could you not just use our react-native integration (from raven-js) with this?

**Comment by springuper** [comment]
raven-js doesn't capture native exceptions, such as jsbundle loading failure, source code execution failure, native modules failure
